# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_id = thecorgimod
mod_version = 3.0.0
maven_group = com.fabbe50.corgimod
archives_name = TheCorgiMod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.9
fabric_api_version = 0.110.0+1.21.1
neoforge_version = 21.1.89

patchouli_version_neoforge = 1.21-89-NEOFORGE-SNAPSHOT
patchouli_version_fabric = 1.21-89-FABRIC-SNAPSHOT
emi_version = 1.1.20+1.21.1
curios_version = 9.0.9+1.21
mod_menu_version = 11.0.1
trinkets_version = 3.10.0
cloth_config_version = 15.0.127
sbl_version=1.16.7
spark_version=1.10.138