modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"

[[mods]]
modId="corgis"
version="${file.jarVersion}"
displayName="The Corgi Mod"
#displayURL=""
#logoFile=""
#credits=""
authors="fabbe50"
description='''
A mod about Corgis
'''

[[dependencies.corgis]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.corgis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
