modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"

[[mods]]
modId="corgis"
version="${file.jarVersion}"
displayName="The Corgi Mod"
#displayURL=""
#logoFile=""
#credits=""
authors="fabbe50"
description='''
A mod about Corgis
'''

[[dependencies.corgis]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.corgis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
